import { Injectable, Logger, OnModuleInit } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';
import { Model } from 'mongoose';
import { Job } from './job.schema';
import { QuestionsService } from '../questions/questions.service';

@Injectable()
export class JobsService implements OnModuleInit {
  private readonly logger = new Logger(JobsService.name);

  constructor(
    @InjectModel(Job.name) private jobModel: Model<Job>,
    private questionsService: QuestionsService,
  ) {}

  async onModuleInit() {
    await this.seedJobs();
  }

  async seedJobs() {
    const jobs = [
      { job_id: 1, title: 'Python Developer (Fresher)', category: 'Software Development', difficulty: 'Beginner' },
      { job_id: 2, title: 'Frontend Developer (Fresher)', category: 'Software Development', difficulty: 'Beginner' },
      { job_id: 3, title: 'Communication & HR Round', category: 'HR & Management', difficulty: 'Beginner' },
      { job_id: 4, title: 'Aptitude & Problem-Solving', category: 'General Aptitude', difficulty: 'Beginner' },
    ];

    const jobQuestions = {
      "Python Developer (Fresher)": [
        "Can you start by introducing yourself and your experience with Python?",
        "What made you choose Python as your primary programming language?",
        "How would you explain Python to someone who has never coded before?",
        "Can you explain the difference between a list and a tuple in Python?",
        "When would you prefer using a dictionary over a list?",
        "What are Python functions, and why are they useful?",
        "Can you walk me through how you would write a simple function?",
        "What is the difference between local and global variables?",
        "Have you worked with loops in Python? Can you give an example?",
        "What’s the difference between a for loop and a while loop?",
        "Can you explain what list comprehension is with a simple example?",
        "How does error handling work in Python?",
        "Have you used try-except blocks? When would you use them?",
        "What are modules and packages in Python?",
        "Can you explain how you would import and use a module?",
        "What is object-oriented programming in Python?",
        "Can you explain the concept of classes and objects?",
        "What is inheritance, and why is it useful?",
        "Have you used any Python libraries? Which ones?",
        "Can you explain how you would read a file in Python?",
        "How would you write data into a file?",
        "What is the difference between append and write modes?",
        "Have you worked with APIs in Python?",
        "How would you send a request to an API?",
        "What is JSON, and how is it used in Python?",
        "Can you explain what pip is used for?",
        "How do you install and manage Python packages?",
        "What is virtual environment, and why is it important?",
        "Have you worked on any Python projects? Can you describe one?",
        "What challenges did you face in your project?",
        "How do you debug your Python code?",
        "What is indentation in Python, and why is it important?",
        "What happens if indentation is incorrect?",
        "Can you explain slicing in Python?",
        "What is the difference between shallow copy and deep copy?",
        "Have you worked with data structures in Python?",
        "What is a set, and when would you use it?",
        "Can you explain lambda functions?",
        "What is recursion? Have you used it before?",
        "How would you optimize a slow Python program?",
        "Have you used Python for automation tasks?",
        "Can you explain how you would parse a CSV file?",
        "What is the difference between Python 2 and Python 3?",
        "How do you handle large data in Python?",
        "What is the use of decorators in Python?",
        "Have you heard about generators? How do they work?",
        "What is the difference between list and generator?",
        "How do you test your Python code?",
        "What are your strengths in Python?",
        "Where do you see yourself improving in Python?",
      ],
      "Frontend Developer (Fresher)": [
        "Can you introduce yourself and tell me about your interest in frontend development?",
        "What do you understand by frontend development?",
        "What technologies have you worked with so far?",
        "Can you explain the difference between HTML, CSS, and JavaScript?",
        "How does a web page actually load in the browser?",
        "What is the DOM, and why is it important?",
        "Can you explain how JavaScript interacts with the DOM?",
        "What are semantic HTML tags?",
        "Why is responsive design important?",
        "How do you make a website responsive?",
        "What is CSS Flexbox?",
        "Can you explain CSS Grid?",
        "What is the box model in CSS?",
        "What is the difference between class and id?",
        "What is specificity in CSS?",
        "What is JavaScript, and why is it used?",
        "What is the difference between var, let, and const?",
        "Can you explain functions in JavaScript?",
        "What are arrow functions?",
        "What is event handling in JavaScript?",
        "Can you explain asynchronous programming?",
        "What are promises?",
        "What is async/await?",
        "How do you fetch data from an API?",
        "What is JSON?",
        "Have you used any frontend frameworks?",
        "What is React, and why is it popular?",
        "What are components in React?",
        "What is state in React?",
        "What is props in React?",
        "What is the difference between state and props?",
        "What is a single-page application?",
        "What are lifecycle methods?",
        "What is useEffect?",
        "What is useState?",
        "How do you debug frontend issues?",
        "How do you optimize performance in frontend apps?",
        "What is lazy loading?",
        "How do you handle errors in UI?",
        "What is accessibility in web development?",
        "What tools do you use for development?",
        "What is version control?",
        "Have you used Git?",
        "How do you deploy a frontend app?",
        "What is browser compatibility?",
        "What are your favorite frontend tools?",
        "What challenges have you faced in frontend development?",
        "Can you explain one project you worked on?",
        "What do you enjoy most about frontend development?",
        "What do you want to learn next in frontend?",
      ],
      "Communication & HR Round": [
        "Can you introduce yourself?",
        "Tell me about your background.",
        "What are your strengths?",
        "What are your weaknesses?",
        "Why should we hire you?",
        "Where do you see yourself in 5 years?",
        "Why did you choose your field?",
        "What motivates you?",
        "Tell me about a challenge you faced.",
        "How do you handle pressure?",
        "How do you manage your time?",
        "Describe a situation where you worked in a team.",
        "What role do you usually take in a team?",
        "How do you handle conflict?",
        "What is your biggest achievement?",
        "What is your biggest failure?",
        "What did you learn from your mistakes?",
        "How do you handle feedback?",
        "Are you comfortable working under deadlines?",
        "What are your hobbies?",
        "How do you improve your communication skills?",
        "Describe a time you solved a problem.",
        "What does success mean to you?",
        "What does leadership mean to you?",
        "How do you prioritize tasks?",
        "What kind of work environment do you prefer?",
        "How do you stay motivated?",
        "What makes you unique?",
        "What are your career goals?",
        "How do you handle criticism?",
        "Tell me about a time you failed.",
        "How do you handle stress?",
        "What do you expect from this role?",
        "Why do you want to join our company?",
        "What do you know about our company?",
        "How do you deal with difficult people?",
        "What are your short-term goals?",
        "How do you learn new skills?",
        "What is your biggest strength in communication?",
        "What is your biggest weakness in communication?",
        "How do you handle rejection?",
        "Describe yourself in one word.",
        "What are your values?",
        "How do you handle multitasking?",
        "What inspires you?",
        "What is your proudest moment?",
        "How do you deal with failure?",
        "What makes a good team player?",
        "Do you prefer working alone or in a team?",
        "Do you have any questions for us?",
      ],
      "Aptitude & Problem-Solving": [
        "How do you approach solving a new problem?",
        "Can you walk me through your thinking process?",
        "If a train travels 60 km in 1 hour, how far will it go in 2.5 hours?",
        "How would you solve a basic percentage problem?",
        "What is your approach to time and work problems?",
        "Can you explain how you solve ratio problems?",
        "How do you handle logical puzzles?",
        "What is your strategy for solving quantitative questions?",
        "How do you avoid mistakes in calculations?",
        "Can you solve problems under time pressure?",
        "How do you break down a complex problem?",
        "What is your approach to reasoning questions?",
        "How do you check your answers?",
        "Can you explain your thought process clearly?",
        "What is more important: speed or accuracy?",
        "How do you improve your aptitude skills?",
        "Can you solve puzzles regularly?",
        "What tools do you use for practice?",
        "How do you stay calm during tests?",
        "What is your strategy for elimination?",
        "Can you solve number series problems?",
        "What is your approach to data interpretation?",
        "How do you handle tricky questions?",
        "What do you do if you don’t know the answer?",
        "How do you manage time in exams?",
        "Can you explain a problem you solved recently?",
        "How do you learn from mistakes?",
        "What is your approach to probability questions?",
        "How do you handle pressure in exams?",
        "What motivates you to solve problems?",
        "Can you explain a logical reasoning question?",
        "What is your approach to puzzles?",
        "How do you improve speed?",
        "What is your approach to accuracy?",
        "How do you analyze your performance?",
        "What is your strategy for mock tests?",
        "How do you deal with difficult questions?",
        "What is your approach to shortcuts?",
        "How do you balance speed and accuracy?",
        "What is your biggest challenge in aptitude?",
        "How do you stay consistent in practice?",
        "What resources do you use?",
        "How do you improve logical thinking?",
        "What is your approach to decision making?",
        "How do you solve unfamiliar problems?",
        "How do you handle failure in tests?",
        "What is your learning strategy?",
        "What is your biggest strength in problem solving?",
        "What is your weakness in aptitude?",
        "How do you plan to improve?",
      ]
    };

    this.logger.log('Seeding jobs list...');
    for (const job of jobs) {
      await this.jobModel.updateOne(
        { job_id: job.job_id },
        { $set: job },
        { upsert: true },
      );
      
      const questions = jobQuestions[job.title];
      if (questions) {
        await this.questionsService.saveGeneralQuestions(job.job_id, questions, job.difficulty);
      }
    }
    this.logger.log(`Successfully seeded ${jobs.length} jobs and their questions.`);
  }

  async findAll() {
    return this.jobModel.find().sort({ job_id: 1 }).exec();
  }
}
